#!/bin/bash

# Initialise Huion tablet buttons and functionality using xsetwacom utility
# Requires xf86-input-wacom, xorg-xinput, digimend-kernel-drivers-dkms-git
# May only work in X, not Wayland

# Set button functions - these go from the top of the pad down
xsetwacom set "HID 256c:006d Pad pad" button 1 key +Ctrl S -Ctrl   # Top button - Save
xsetwacom set "HID 256c:006d Pad pad" button 2 key +Ctrl +Shift Z -Shift -Ctrl # Button 2 - Redo
xsetwacom set "HID 256c:006d Pad pad" button 3 key +Ctrl Z -Ctrl # Button 3 - Undo
xsetwacom set "HID 256c:006d Pad pad" button 8 key Ctrl   # Button 4 - Control
xsetwacom set "HID 256c:006d Pad pad" button 9 key Shift  # Button 5 - 
xsetwacom set "HID 256c:006d Pad pad" button 10 key e  # Button 6 - Eraser
xsetwacom set "HID 256c:006d Pad pad" button 11 key 7  # Button 7 - 
xsetwacom set "HID 256c:006d Pad pad" button 12 key 8  # Button 8 - 


# Set pen to use display 1
xsetwacom set "HID 256c:006d stylus" MapToOutput DP-1

# Set pen button functions
xsetwacom set "HID 256c:006d stylus" button 1 1  # Button at the top - left click
xsetwacom set "HID 256c:006d stylus" button 2 2  # Barrel button closer to tip - middle mouse button
xsetwacom set "HID 256c:006d stylus" button 3 3  # Barrel button closer to tip - right click

echo "Set up tablet button+display mapping"
