#!/usr/bin/bash

swaylock -i /home/gbrnt/Pictures/bg-lock.jpg \
    --inside-color 262626 \
    --inside-ver-color 262626 \
    --inside-wrong-color 262626 \
    --ring-color 262626 \
    --ring-ver-color ff4444 \
    --ring-wrong-color ff0000 \
    --key-hl-color ff4444 \
    --line-color 00000000 \
    --text-color ffffff
