#!/bin/bash

export XKB_DEFAULT_LAYOUT=gb
export XKB_DEFAULT_OPTIONS=ctrl:nocaps
export XDG_CURRENT_DESKTOP=sway
export _JAVA_AWT_WM_NONREPARENTING=1
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
#/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
sway
